# Server
server.port=8080

# DataSource — PostgreSQL - local
#spring.datasource.url=jdbc:postgresql://localhost:5432/kabarent
#spring.datasource.username=myuser
#spring.datasource.password=mypassword
#spring.datasource.driver-class-name=org.postgresql.Driver

#Server
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# CORS (configured in CorsConfig.java)
app.cors.allowed-origins=http://localhost:5173
